- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400  # 1 Day
  become: true

- name: Install system tool debian packages
  ansible.builtin.apt:
    pkg:
      - can-utils
      - net-tools
      - terminator
      - tig
      - tree
      - vim
    state: present
  become: true
