- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400  # 1 Day
  become: true

- name: Install doxygen
  ansible.builtin.apt:
    pkg:
      - doxygen
    state: present
  become: true
